enum Routes {
  // auth routes
  login,
  phone,
  otp,

  // general routes
  splash,
  welcome,
  settings,
  notifications,
  balance,
  wallet,
  deposit,
  withdraw,
  vendorManagePaymentMethods,
  transactions,
  safety,
  about,
  privacyPolicy,
  termsAndConditions,
  scanner,
  support,
  loading,
  test,
  profile,
  editProfile,
  paymentMethods,
  shippingMethods,
  payment,
  paymentSuccess,
  paymentWebView,
  walletPaymentMethods,

  // chat routes
  chat,
  conversations,

  // customer routes
  customer,
  cart,
  checkout,
  search,
  searchFilters,
  customerServices,
  customerOrders,
  customerOrderDetails,
  customerProducts,
  customerProductDetails,
  customerRequests,
  customerAddRequest,
  customerOffers,
  customerRequestPayment,
  accidentAssistance,
  brands,
  models,
  generations,
  feesAndTaxs,
  customerProfile,
  changeCity,
  partsCategories,
  parts,
  wheels,
  wheelsResults,

  // vendor routes
  vendor,
  vendorOrders,
  vendorRequests,
  vendorRegister,
  vendorProducts,
  vendorAddProduct,
  vendorProfile,
  vendorEditProfile,
  vendorProductDetails,
  vendorRegisterStep1,
  vendorRegisterStep2,
  vendorRegisterStep3,
  vendorRequestDetails,
  vendorProposeOffer,
}
